gestor/urls.py
from django.urls import path, include

from . import routers
from . import views

from django.contrib.auth import views as auth_views

from wkhtmltopdf.views import PDFTemplateView

app_name = 'gestor'

urlpatterns = [
    path(
        'pdf/', 
        PDFTemplateView.as_view(
            template_name='gestor/producto/ProductoDetail.html', 
            filename='sss.pdf',
            cmd_options={'quiet': True,}
        )
        , name='pdf'),
    path('', views.HomeView.as_view(), name='home'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='gestor/base.html'), name='logout'),
]


urlpatterns += [
    path('empresa/', views.EmpresaCreate.as_view(), name='create_empresa'),
    path('empresa/<slug:rfc>/', views.EmpresaContactoList.as_view(), name='detail_empresa'),
    path('empresa/<slug:rfc>/actualizar/', views.EmpresaUpdate.as_view(), name='update_empresa'),
    path('empresa/<slug:rfc>/eliminar/', views.EmpresaDelete.as_view(), name='delete_empresa'),
    path('empresas/', views.EmpresaList.as_view(), name='list_empresa'),
]

urlpatterns += [
    path('empresa/<slug:rfc>/archivo/', views.EmpresaArchivoCreate.as_view(), name='upload_empresa_archivo'),
    path('empresa/<slug:rfc>/archivos/', views.EmpresaArchivoList.as_view(), name='list_empresa_archivo'),
]

urlpatterns += [
    path('contactos/', views.ContactoList.as_view(), name='list_contacto'),
    path('empresa/<slug:rfc>/contactos/', views.EmpresaContactoList.as_view(), name='list_contacto_empresa'),
    path('empresa/<slug:rfc>/contacto/', views.ContactoCreate.as_view(), name='create_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/', views.ContactoDetail.as_view(), name='detail_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/actualizar/', views.ContactoUpdate.as_view(), name='update_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/eliminar/', views.ContactoDelete.as_view(), name='delete_contacto'),
]

urlpatterns += [
    path('productos/', views.ProductoList.as_view(), name='list_producto'),
    path('producto/', views.ProductoCreate.as_view(), name='create_producto'),
    path('producto/<int:id>/', views.ProductoUpdate.as_view(), name='detail_producto'),
    path('producto/<int:id>/actualizar/', views.ProductoUpdate.as_view(), name='update_producto'),
    path('producto/<int:id>/eliminar/', views.ProductoDelete.as_view(), name='delete_producto'),
]

urlpatterns += [
    path('cotizaciones/', views.CotizacionList.as_view(), name='list_cotizacion'),
    path('empresa/<slug:rfc>/cotizaciones/', views.EmpresaCotizacionList.as_view(), name='list_cotizacion_empresa'),
    path('empresa/<slug:rfc>/cotizacion/', views.CotizacionCreate.as_view(), name='create_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/', views.CotizacionDetail.as_view(), name='detail_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/actualizar/', views.CotizacionUpdate.as_view(), name='update_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto_cotizado/<int:id>/eliminar/', views.ProductoCotizadoDelete.as_view(), name='delete_prodcuto_cotizado'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto_cotizado/<int:id>/actualizar/', views.ProductoCotizadoUpdate.as_view(), name='update_producto_cotizado'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto/<int:id>/agregar/', views.ProductoAdd.as_view(), name='add_producto'),
]

urlpatterns += [
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/pdf/', views.CotizacionGeneratePDF.as_view(), name='generate_pdf_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/pdf/template/', views.CotizacionGeneratePDFView.as_view(), name='template_pdf_cotizacion'),
]

urlpatterns += [
    path('facturas/', views.FacturaList.as_view(), name='list_factura'),
    path('empresa/<slug:rfc>/facturas/', views.EmpresaFacturaList.as_view(), name='list_factura_empresa'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/facturar/', views.FacturaCreate.as_view(), name='create_factura'),
    path('empresa/<slug:rfc>/factura/<int:id>/', views.FacturaDetail.as_view(), name='detail_factura'),
    path('empresa/<slug:rfc>/factura/<int:id>/archivo/', views.FacturaArchivosUpload.as_view(), name='upload_archivo'),
]

urlpatterns += [
    path('api/', include(routers.router.urls)),
]

revolucion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestor/', include('gestor.urls')),
]

gestor/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render, redirect

from django.urls import reverse
from django.template.loader import get_template
from django.http import HttpResponse

from django.views import View
from django.views.generic import ListView
from django.views.generic.base import TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView

from wkhtmltopdf.views import PDFTemplateView

from .models import Empresa
from .forms import EmpresaCreateForm, EmpresaUpdateForm

from .models import EmpresaArchivo
from .forms import EmpresaArchivoCreateForm

from .models import Contacto
from .forms import ContactoCreateForm

from .models import Producto
from .forms import ProductoCreateForm

from .models import Cotizacion
from .forms import CotizacionCreateForm, CotizacionUpdateForm

from .models import ProductoCotizado
from .forms import ProductoAddForm, ProductoCotizadoUpdateForm

from .models import Factura
from .forms import FacturaCreateForm

from .models import FacturaArchivos
from .forms import FacturaArchivosUploadForm

from .forms import UserSignUpForm

class HomeView(TemplateView):
    template_name = 'gestor/home.html'

class EmpresaList(TemplateView):
    template_name = 'gestor/empresa/EmpresaList.html'

class EmpresaCreate(CreateView):
    template_name = 'gestor/empresa/EmpresaCreate.html'
    model = Empresa
    form_class = EmpresaCreateForm

    def get_success_url(self, **kwargs):
        return reverse('gestor:detail_empresa', kwargs={'rfc': self.object.rfc })

class EmpresaUpdate(UpdateView):
    template_name = 'gestor/empresa/EmpresaUpdate.html'
    model = Empresa
    form_class = EmpresaUpdateForm
    context_object_name = 'empresa'
    pk_url_kwarg = 'rfc'

    def get_success_url(self, **kwargs):
        return reverse('gestor:detail_empresa', kwargs={'rfc': self.object.rfc})

class EmpresaDelete(DeleteView):
    template_name = 'gestor/empresa/EmpresaDelete.html'
    model = Empresa
    context_object_name = 'empresa'
    pk_url_kwarg = 'rfc'

    def get_success_url(self, **kwargs):
        return reverse('gestor:list_empresa')

class EmpresaArchivoCreate(CreateView):
    template_name = 'gestor/empresa_archivo/EmpresaArchivoCreate.html'
    model = EmpresaArchivo
    form_class = EmpresaArchivoCreateForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            print('ddd')
            return redirect(self.get_success_url(**kwargs))
        else:
            print('shdbsdbsdjsdbsjdbsjdbsjdd')
            empresa = Empresa.objects.get(rfc=self.kwargs['rfc'])
            return render(request, self.template_name, {'form': form, 'empresa': empresa,})


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def form_valid(self, form):
        form.instance.empresa = Empresa.objects.get(pk=self.kwargs['rfc'])
        print(form.instance.empresa)
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('gestor:detail_empresa',  kwargs={'rfc': self.kwargs['rfc']})

class EmpresaArchivoList(SingleObjectMixin, ListView):
    template_name = 'gestor/empresa_archivo/EmpresaArchivoList.html'
    model = Empresa
    pk_url_kwarg='rfc'
    context_object_name = 'empresa'
    paginate_by = 25

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Empresa.objects.all())
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.archivos.all()
    

class ContactoList(TemplateView):
    template_name = 'gestor/contacto/ContactoList.html'

class EmpresaContactoList(SingleObjectMixin, ListView):
    template_name = 'gestor/contacto/ContactoList(Empresa).html'
    model = Empresa
    pk_url_kwarg='rfc'
    context_object_name = 'empresa'
    paginate_by = 25

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Empresa.objects.all())
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.contacto_set.all()

class ContactoCreate(CreateView):
    template_name = 'gestor/contacto/ContactoCreate.html'
    model = Contacto
    form_class = ContactoCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def form_valid(self, form):
        form.instance.empresa = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('gestor:list_contacto_empresa', kwargs={'rfc': self.kwargs['rfc']})

class ContactoDetail(SingleObjectMixin, ListView):
    template_name = 'gestor/contacto/ContactoDetail.html'
    model = Contacto
    pk_url_kwarg='id'
    context_object_name = 'contacto'
    paginate_by = 25

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Contacto.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def get_queryset(self):
        return self.object.cotizacion_set.all()

class ContactoUpdate(UpdateView):
    template_name='gestor/contacto/ContactoUpdate.html'
    model = Contacto
    form_class = ContactoCreateForm
    context_object_name = 'contacto'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def get_success_url(self, **kwargs):
        return reverse('gestor:list_contacto_empresa',  kwargs={'rfc': self.kwargs['rfc']})

class ContactoDelete(DeleteView):
    template_name='gestor/contacto/ContactoDelete.html'
    model = Contacto
    context_object_name = 'contacto'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def get_success_url(self, **kwargs):
        return reverse('gestor:list_contacto_empresa',  kwargs={'rfc': self.kwargs['rfc']})

# Cotización

class CotizacionList(TemplateView):
    template_name = 'gestor/cotizacion/CotizacionList.html'

class EmpresaCotizacionList(SingleObjectMixin, ListView):
    template_name = 'gestor/cotizacion/CotizacionList(Empresa).html'
    model = Empresa
    pk_url_kwarg='rfc'
    context_object_name = 'empresa'
    paginate_by = 25

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Empresa.objects.all())
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.cotizaciones.all()

class CotizacionCreate(CreateView):
    template_name = 'gestor/cotizacion/CotizacionCreate.html'
    form_class = CotizacionCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def form_valid(self, form):
        form.instance.empresa = Empresa.objects.get(rfc=self.kwargs['rfc'])
        form.instance.usuario = self.request.user
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        cotizacion_kwargs = {
            'rfc': self.kwargs['rfc'],
            'pk': self.object.pk,
        }
        return reverse('gestor:detail_cotizacion', kwargs=cotizacion_kwargs)

class CotizacionDetail(DetailView):
    template_name = 'gestor/cotizacion/CotizacionDetail.html'
    model = Cotizacion
    context_object_name = 'cotizacion'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        context['producto_cotizado_list'] = self.object.productos_cotizados.all()
        context['factura'] = None
        if self.object.is_factura:
            context['factura'] = self.object.factura
        return context

class CotizacionUpdate(UpdateView):
    template_name = 'gestor/cotizacion/CotizacionUpdate.html'
    model = Cotizacion
    form_class = CotizacionUpdateForm
    context_object_name = 'cotizacion'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])
        return context

    def get_success_url(self, **kwargs):
        cotizacion_kwargs = {
            'rfc': self.kwargs['rfc'],
            'pk': self.object.pk,
        }
        return reverse('gestor:detail_cotizacion', kwargs=cotizacion_kwargs)

# Productos Cotizados

class ProductoCotizadoUpdate(UpdateView):
    template_name='gestor/producto/ProductoCotizadoUpdate.html'
    model = ProductoCotizado
    form_class = ProductoCotizadoUpdateForm
    context_object_name = 'producto_cotizado'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['empresa'] = Empresa.objects.get(rfc=self.kwargs['rfc'])

templates/gestor/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

  <title>Gestor: {% block title %}{% endblock %}</title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <!-- Getor Style -->
  <link rel="stylesheet" href="{% static 'css/gestor.css' %}">

  <!-- VueJs -->
  <script src="{% static 'js/vue.js' %}"></script>

  <!-- VueJs resource -->
  <script src="{% static 'js/vue-resource.min.js' %}"></script>

  <!-- jQuery -->
  <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>

  <!-- popper -->
  <script src="{% static 'js/popper.min.js' %}"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

</head>

<body>
  <header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-light fixed-top">
      <a class="navbar-brand" href="{% url 'gestor:home' %}">Gestor</a>
      <button class="navbar-toggler" type="button"
        data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gestor:list_empresa' %}">Empresas<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gestor:list_factura' %}">Facturas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gestor:list_cotizacion' %}">Cotizaciones</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gestor:list_producto' %}">Productos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gestor:list_contacto' %}">Contactos</a>
          </li>
        </ul>

        <div id="login" class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="session-dropdown" data-toggle="dropdown">
              {% if not request.user.is_authenticated %}
                Inciar sesión
              {% else %}
                {{request.user.username}}
              {% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="session-dropdown">
              {% if not request.user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'gestor:login' %}">Iniciar sesión</a>
                <a class="dropdown-item" href="{% url 'gestor:signup' %}">Registrar usuario</a>
              {% else %}
                <a class="dropdown-item" href="{% url 'gestor:logout' %}">Cerrar sesion</a>
              {% endif %}
            </div>
        </div>

      </div>
    </nav>
  </header>

      <!-- Begin page content -->
  <main role="main" class="container" style="padding: 60px 15px 0;">
    <div class="row">
      <div class="col-lg-3">
        <div class="list-group my-5">
          {% block actions %}{% endblock %}
        </div>
      </div>
      <div class="col-lg-9">
        <div class="card-outline-primary my-4">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </main>

  <footer class="footer">
    <div class="container">
      <span class="text-muted"><a href="https://gitlab.com/eersya/revolucion.git">Code</a></span>
    </div>
  </footer>

  <!-- Custom scripts -->
  {% block scripts %}{% endblock %}

  </script>

</body>
<html>

templates/gestor/home.html
{% extends "gestor/base.html" %}