gestor/urls.py
from django.urls import path, include

from . import routers
from . import views

from django.contrib.auth import views as auth_views

from wkhtmltopdf.views import PDFTemplateView

app_name = 'gestor'

urlpatterns = [
    path(
        'pdf/', 
        PDFTemplateView.as_view(
            template_name='gestor/producto/ProductoDetail.html', 
            filename='sss.pdf',
            cmd_options={'quiet': True,}
        )
        , name='pdf'),
    path('', views.HomeView.as_view(), name='home'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='gestor/base.html'), name='logout'),
]


urlpatterns += [
    path('empresa/', views.EmpresaCreate.as_view(), name='create_empresa'),
    path('empresa/<slug:rfc>/', views.EmpresaContactoList.as_view(), name='detail_empresa'),
    path('empresa/<slug:rfc>/actualizar/', views.EmpresaUpdate.as_view(), name='update_empresa'),
    path('empresa/<slug:rfc>/eliminar/', views.EmpresaDelete.as_view(), name='delete_empresa'),
    path('empresas/', views.EmpresaList.as_view(), name='list_empresa'),
]

urlpatterns += [
    path('empresa/<slug:rfc>/archivo/', views.EmpresaArchivoCreate.as_view(), name='upload_empresa_archivo'),
    path('empresa/<slug:rfc>/archivos/', views.EmpresaArchivoList.as_view(), name='list_empresa_archivo'),
]

urlpatterns += [
    path('contactos/', views.ContactoList.as_view(), name='list_contacto'),
    path('empresa/<slug:rfc>/contactos/', views.EmpresaContactoList.as_view(), name='list_contacto_empresa'),
    path('empresa/<slug:rfc>/contacto/', views.ContactoCreate.as_view(), name='create_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/', views.ContactoDetail.as_view(), name='detail_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/actualizar/', views.ContactoUpdate.as_view(), name='update_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/eliminar/', views.ContactoDelete.as_view(), name='delete_contacto'),
]

urlpatterns += [
    path('productos/', views.ProductoList.as_view(), name='list_producto'),
    path('producto/', views.ProductoCreate.as_view(), name='create_producto'),
    path('producto/<int:id>/', views.ProductoUpdate.as_view(), name='detail_producto'),
    path('producto/<int:id>/actualizar/', views.ProductoUpdate.as_view(), name='update_producto'),
    path('producto/<int:id>/eliminar/', views.ProductoDelete.as_view(), name='delete_producto'),
]

urlpatterns += [
    path('cotizaciones/', views.CotizacionList.as_view(), name='list_cotizacion'),
    path('empresa/<slug:rfc>/cotizaciones/', views.EmpresaCotizacionList.as_view(), name='list_cotizacion_empresa'),
    path('empresa/<slug:rfc>/cotizacion/', views.CotizacionCreate.as_view(), name='create_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/', views.CotizacionDetail.as_view(), name='detail_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/actualizar/', views.CotizacionUpdate.as_view(), name='update_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto_cotizado/<int:id>/eliminar/', views.ProductoCotizadoDelete.as_view(), name='delete_prodcuto_cotizado'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto_cotizado/<int:id>/actualizar/', views.ProductoCotizadoUpdate.as_view(), name='update_producto_cotizado'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto/<int:id>/agregar/', views.ProductoAdd.as_view(), name='add_producto'),
]

urlpatterns += [
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/pdf/', views.CotizacionGeneratePDF.as_view(), name='generate_pdf_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/pdf/template/', views.CotizacionGeneratePDFView.as_view(), name='template_pdf_cotizacion'),
]

urlpatterns += [
    path('facturas/', views.FacturaList.as_view(), name='list_factura'),
    path('empresa/<slug:rfc>/facturas/', views.EmpresaFacturaList.as_view(), name='list_factura_empresa'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/facturar/', views.FacturaCreate.as_view(), name='create_factura'),
    path('empresa/<slug:rfc>/factura/<int:id>/', views.FacturaDetail.as_view(), name='detail_factura'),
    path('empresa/<slug:rfc>/factura/<int:id>/archivo/', views.FacturaArchivosUpload.as_view(), name='upload_archivo'),
]

urlpatterns += [
    path('api/', include(routers.router.urls)),
]

revolucion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestor/', include('gestor.urls')),
]

gestor/models.py
from django.db import models

from django.contrib.auth.models import User

from .utils import empresa_directory_path
from .utils import update_producto_cotizado, update_cotizacion
from .utils import get_descripcion

# Dictionaries
class CatalogoClaveProducto(models.Model):
    clave = models.IntegerField(primary_key=True)
    descripcion = models.CharField(max_length=20)

    def __str__(self):
        return '%d' % (self.clave)

#Datos Escenciales para el funcionamiento

class Empresa(models.Model):
    rfc = models.CharField(
        max_length=13,
        primary_key=True,
    )
    razon_social = models.CharField(max_length=40)
    nombre_comercial = models.CharField(
        max_length=40,
        blank=True, 
        null=True,
    )
    correo = models.EmailField(max_length=40)
    telefono = models.CharField(max_length=22)
    BANCOS = (
        (1, 'Bancomer'),
        (2, 'Banamex'),
        (3, 'Banorte'),
        (3, 'IXE'),
        (0, 'N/A'),
    )
    banco = models.IntegerField(
        choices=BANCOS,
        default=0,
    )
    referencia_bancaria = models.IntegerField(default = -1)
    CUIDAD_ESTADO = (
        (1, 'CDMX/CDMX'),
        (2, 'Estado de México/Toluca'),
    )
    USOS_CDFI = (
        ('P01', 'Por definir'),
        ('D10', 'Pagos por servicios educativos (colegiaturas)'),
        ('D09', 'Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones'),
        ('D08', 'Gastos de transportación escolar obligatoria'),
        ('D07', 'Primas por seguros de gastos médicos'),
        ('D06', 'Aportaciones voluntarias al SAR'),
        ('D05', 'Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)'),
        ('D04', 'Donativos'),
        ('D03', 'Gastos funerales'),
        ('D02', 'Gastos médicos por incapacidad o discapacidad'),
        ('D01', 'Honorarios médicos, dentales y gastos hospitalarios'),
        ('I08', 'Otra maquinaria y equipo'),
        ('I07', 'Comunicaciones satelitales'),
        ('I06', 'Comunicaciones telefónicas'),
        ('I05', 'Dados, troqueles, moldes, matrices y herramental'),
        ('I04', 'Equipo de cómputo y accesorios'),
        ('I03', 'Equipo de transporte'),
        ('I02', 'Mobiliario y equipo de oficina por inversiones'),
        ('I01', 'Construcciones'),
        ('G03', 'Gastos en general'),
        ('G02', 'Devoluciones, descuentos o bonificaciones'),
        ('G01', 'Adquisición de mercancías'),
    )
    uso_cdfi = models.CharField(
        max_length=3,
        choices=USOS_CDFI,
        default='P01',
    )
    FORMAS_PAGO = (
        (0, 'Efectivo'),
        (1, 'Cheque nominativo'),
        (2, 'Transferencia electrónicade fondos'),
        (3, 'Por definir'),
    )
    forma_pago = models.IntegerField(
        choices=FORMAS_PAGO,
        default=0,
    )
    METODOS_PAGO = (
        (0, 'PUE'),
        (1, 'PPD'),
    )
    metodo_pago = models.IntegerField(
        choices=METODOS_PAGO,
        default=0,
    )
    TIPOS_COMPROBANTE = (
        (0, 'I'),
        (1, 'E'),
        (2, 'T'),
        (3, 'P'),
        (4, 'N'),
    )
    tipo_comprobante = models.IntegerField(
        choices=TIPOS_COMPROBANTE,
        default=0,
    )
    cuidad_estado = models.IntegerField(
        choices=CUIDAD_ESTADO,
        default=1,
    )
    cp = models.IntegerField(default=-1)
    direccion = models.CharField(
        max_length=100,
        blank=True, 
        null=True,
    )
    direccion_entrega = models.CharField(
        max_length=100,
        blank=True, 
        null=True,
    )
    empresas_asociadas = models.ManyToManyField(
        "Empresa",
        related_name='emprsas_asociadas',
        blank=True, 
    )
    extra_1 = models.TextField(
        max_length=150,
        blank=True, null=True,
    )
    extra_2 = models.TextField(
        max_length=150,
        blank=True, null=True,
    )
    extra_3 = models.TextField(
        max_length=150,
        blank=True, null=True,
    )

    def __str__(self):
        return '%s' % self.rfc

class EmpresaArchivo(models.Model):
    empresa = models.ForeignKey(
        Empresa,
        on_delete=models.CASCADE,
        related_name='archivos',
    )
    archivo = models.FileField(upload_to=empresa_directory_path)
    fecha = models.DateField(auto_now_add=True)


class Contacto(models.Model):
    empresa = models.ForeignKey(
        Empresa,
        on_delete=models.CASCADE,
    )
    nombre = models.CharField(max_length=23)
    correo = models.EmailField(max_length=40)
    extension = models.CharField(
        max_length=5,
        blank=True, 
        null=True,
    )
    telefono = models.CharField(max_length=20)
    celular = models.CharField(
        max_length=20,
        blank=True, 
        null=True,
    )
    PREFIJO_CHOICES = (
        (0, ''),
        (1, 'Sr.'),
        (2, 'Sra.'),
        (3, 'Lic.'),
        (4, 'Ing.'),
    )
    prefijo = models.IntegerField(
        choices=PREFIJO_CHOICES,
        default=0,
    )
    puesto = models.CharField(
        max_length=20,
    )
    extra = models.TextField(
        max_length=150,
        blank=True, 
        null=True,
    )

    def __str__(self):
        return '%d[Nombre:%s]' % (self.id, self.nombre)

# Producto

class Producto(models.Model):
    numero_parte = models.CharField(max_length=40)
    TIPOS_PRODUCTO = (
        ('Prd', 'Producto'),
        ('Srv', 'Servicio'),
    )
    tipo_producto = models.CharField(
        max_length=3,
        choices=TIPOS_PRODUCTO,
        default='Prd',
    )
    UNIDADES_MEDIDA = (
        ('H87', 'Pieza'),
        ('XBX', 'Caja'),
        ('O', 'Otro'),
        ('0', 'No Aplica'),
    )
    unidad_medida = models.CharField(
        max_length=3,
        choices=UNIDADES_MEDIDA,
        default='H87',
    )
    clave = models.ForeignKey(
        CatalogoClaveProducto,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    ALIMENTO_IVA = 0
    SIN_ESPECIFICAR_IVA = 16
    TIPOS_IVA = (
        (ALIMENTO_IVA, 'ALIMENTO(0%)'),
        (SIN_ESPECIFICAR_IVA, 'S/A(16%)'),
    )
    tipo_iva = models.IntegerField(
        choices=TIPOS_IVA,
        default=SIN_ESPECIFICAR_IVA,
    )
    descripcion = models.TextField(
        max_length=100,
        blank=True,
    )


# Cotización

class Cotizacion(models.Model):
    empresa = models.ForeignKey(
        Empresa,
        on_delete=models.SET_NULL,
        blank=True, 
        null=True,
        related_name='cotizaciones',
    )
    usuario = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    referencia = models.CharField(
        max_length=20,
        blank=True, 
        null=True,
    )
    fecha = models.DateField(auto_now_add=True)
    contacto = models.ForeignKey(
        Contacto,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    costo_operacion = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    monto_iva = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    subtotal = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00
    )
    ganancia = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    margen_ganancia = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    inversion = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00
    )
    is_factura = models.BooleanField(default=False)
    extras = models.TextField(
        max_length=300,
        blank=True,
        null=True,
    )

    def __str__(self):
        return '%d[Nombre:%s]' % (self.id,self.referencia)

    def save(self, *args, **kwargs):
        update_cotizacion(self)
        super(Cotizacion, self).save(*args, **kwargs)

# Cuando se cotize un producto, en costo debera de aparecer el costo del producto
# junto con el respectivo margen de ganancia
class ProductoCotizado(models.Model):
    cotizacion = models.ForeignKey(
        Cotizacion,
        on_delete=models.CASCADE,
        related_name='productos_cotizados',
    )
    producto = models.ForeignKey(
        Producto,
        on_delete = models.CASCADE,
    )
    provedor = models.ForeignKey(
        Empresa,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    disponibilidad = models.CharField(
        max_length=10,
    )
    precio = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    costo = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    margen_ganancia = models.PositiveIntegerField(default=0)
    cantidad = models.PositiveIntegerField(default=1)
    monto_iva = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=-1.00,
    )
    importe = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    descripcion = models.TextField(
        max_length=150,
        blank=True,
    )

    def get_descripcion(instance):
        return instance.producto.descripcion

    def __str__(self):
        return '%d[Cotizacion:%d]' % (self.id, self.cotizacion.id)

    def save(self, *args, **kwargs):
        update_producto_cotizado(self)
        super(ProductoCotizado, self).save(*args, **kwargs)
        cotizacion = self.cotizacion
        update_cotizacion(cotizacion)
        cotizacion.save()

    def delete(self, *args, **kwargs):
        cotizacion = self.cotizacion
        super(ProductoCotizado, self).delete(*args, **kwargs)
        update_cotizacion(cotizacion)
        cotizacion.save()


class Factura(models.Model):

templates/gestor/contacto/ContactoCreate.html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block empresa_item_content %}
{% load widget_tweaks %}
{{ object.empresa.rfc }}
<form method="post">{% csrf_token %}
  <div class="row">
    <div class="col">
      <label for="{{ form.prefijo.id_for_label }}">{{ form.prefijo.label_tag }}</label>
      {{ form.prefijo|add_class:'form-control' }}
    </div>
    <div class="col">
      <label for="{{ form.puesto.id_for_label }}">{{ form.puesto.label_tag }}</label>
      {{ form.puesto|add_class:'form-control' }}
    </div>
    <div class="col">
      <label for="{{ form.nombre.id_for_label }}">{{ form.nombre.label_tag }}</label>
      {{ form.nombre|add_class:'form-control' }}
    </div>
  </div>
  <div class="row">
    <div class="col">
      <label for="{{ form.correo.id_for_label }}">{{ form.correo.label_tag }}</label>
      {{ form.correo|add_class:'form-control' }}
    </div>
    
  </div>
  <div class="row">
    <div class="col">
      <label for="{{ form.extension.id_for_label }}">{{ form.extension.label_tag }}</label>
      {{ form.extension|add_class:'form-control' }}
    </div>
    <div class="col">
      <label for="{{ form.telefono.id_for_label }}">{{ form.telefono.label_tag }}</label>
      {{ form.telefono|add_class:'form-control' }}
    </div>
    <div class="col">
      <label for="{{ form.celular.id_for_label }}">{{ form.celular.label_tag }}</label>
      {{ form.celular|add_class:'form-control' }}
    </div>
  </div>
  <div class="row">
  <div class="col">
      <label for="{{ form.extra.id_for_label }}">{{ form.extra.label_tag }}</label>
      {{ form.extra|add_class:'form-control' }}
    </div>
  </div>
  <input type="submit" class="btn btn-lg btn-secondary my-2" value="Registrar Contacto">
</form>
{% endblock %}

templates/gestor/contacto/ContactoDelete.html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block  empresa_item_content %}
<form method="post"> {% csrf_token %}
  <h5>¿Estas seguro de eliminar el contacto {{ contacto.nombre }}?</h5>
  <input type="submit" class="btn btn-danger btn-lg my-2" value="Eliminar Contacto">
</form>
{% endblock %}

templates/gestor/contacto/ContactoDetail.html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block empresa_item_content %}
<h3>Contacto: <a href="{% url 'gestor:detail_contacto' empresa.rfc contacto.id %}">#{{contacto.id}}</a></h3>
<dl class="row">
  <dt class="col-sm-3">Nombre:</dt>
  <dd class="col-sm-9">{{contacto.prefijo}} {{contacto.nombre}}</dd>

  <dt class="col-sm-3">Puesto:</dt>
  <dd class="col-sm-9">{{contacto.puesto}}</dd>

  <dt class="col-sm-3">Correo:</dt>
  <dd class="col-sm-9">{{contacto.correo}}</dd>

  <dt class="col-sm-3">Télefono:</dt>
  <dd class="col-sm-9">
    <dl class="row">
      <dt class="col-sm-3">Extensión:</dt>
      <dd class="col-sm-9">{{contacto.extension}}</dd>

      <dt class="col-sm-3">Número:</dt>
      <dd class="col-sm-9">{{contacto.telefono}}</dd>
    </dl>
  </dd>

  <dt class="col-sm-3">Celular:</dt>
  <dd class="col-sm-9">{{contacto.celular}}</dd>

  <dt class="col-sm-3">Extra:</dt>
  <dd class="col-sm-9"><p>{{contacto.extra}}</p></dd>
</dt>
<h6>Facturas: </h6>
<table class="table table-hover" style="width:100%">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Fecha</th>
        <th scope="col">Costo De Operación</th>
        <th scope="col">Monto IVA</th>
        <th scope="col">Total</th>
      </tr>
    </thead>
    {% for cotizacion in object_list %}
      <tr>
      {% if cotizacion.is_factura %}
        <th scope="col" class="table-success">
          <a href="{% url 'gestor:detail_cotizacion' empresa.rfc cotizacion.id %}">
            {{cotizacion.id}}
          </a>
        </th>
      {% else %}
        <th scope="col" class="table-danger">
          <a href="{% url 'gestor:detail_cotizacion' empresa.rfc cotizacion.id %}">
            {{cotizacion.id}}
          </a>
        </th>
      {% endif %}
        <th scope="col">{{cotizacion.fecha}}</th>
        <th scope="col">${{cotizacion.costo_de_operacion}}</th>
        <th scope="col">${{cotizacion.monto_iva}}</th>
        <th scope="col">${{cotizacion.total}}</th>
      </tr>
    {% endfor %}
  </table>

</div>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ i }} <span class="sr-only">actual</span></a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Siguiente</span>
        </a>
      </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Siguiente</span>
      </a>
    </li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

templates/gestor/contacto/ContactoList(Empresa).html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block empresa_item_content %}

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'gestor:list_factura_empresa' empresa.rfc %}">Facturas</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'gestor:list_cotizacion_empresa' empresa.rfc %}">Cotizaciones</a>
  </li>
  <li class="nav-item">
  <li class="nav-item">
    <a class="nav-link active" href="#">Contactos</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="{% url 'gestor:list_empresa_archivo' empresa.rfc %}">Extras</a>
  </li>
</ul>
<div class="my-2">
  <h5>
    Contactos:
    <a class="btn btn-secondary" role="button" href="{% url 'gestor:create_contacto' empresa.rfc %}">Registar Contacto</a>
  </h5>
</div>

<table class="table table-hover" style="width:100%">
    <thead class="thead-light">
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Correo</th>
        <th scope="col">Teléfono</th>
      </tr>
    </thead>
    {% for contacto in object_list %}
      <tr class="clickable-tr" href="{% url 'gestor:detail_contacto' empresa.rfc contacto.id %">
        <th scope="col">
          <div id="contactoAccordion{{contacto.id}}">

            <div class="card">
              <div class="car-header" id="headingThree">
                <h6 class="mb-0">
                  <button class="btn btn-link" data-toggle="collapse" data-target="#collapseContacto{{contacto.id}}"
                    aria-expanded="true" aria-controls="collapseContacto{{contacto.id}}">
                    {{ contacto.get_prefijo_display }} {{ contacto.nombre }}
                  </button>
                </h6>
              </div>
            </div>

            <div id="collapseContacto{{contacto.id}}" class="collapse not-show"
              aria-labelledby="headingThree" data-parent="contactoAccordion{{contacto.id}}">
              <div class="card-body">
                <h6>
                  <a class="btn btn-outline-warning mx-2" role="button"
                    href="{% url 'gestor:update_contacto' empresa.rfc contacto.id %}">
                    Actualizar
                  </a>
                  <a class="btn btn-outline-danger" role="button"
                    href="{% url 'gestor:delete_contacto' empresa.rfc contacto.id %}">
                    Eliminar
                  </a>
                </h6>
              </div>
            </div>

            <a href="#">

            </a>
          </div>
        </th>
        <th scope="col">
          {{ contacto.correo }}
        </th>
        <th scope="col">
          {{ contacto.telefono }}
        </th>
      </tr>
    {% endfor %}
  </table>

</div>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ i }} <span class="sr-only">actual</span></a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Siguiente</span>
        </a>
      </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Siguiente</span>
      </a>
    </li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

templates/gestor/contacto/ContactoList.html
{% extends "gestor/base.html" %}

{% block title %}
  Contactos
{% endblock %}

{% block actions %}
  <h2>Contactos</h2>

  <div class="card my-2" style="width: 15rem;">
    <div class="card-body">
      <h5 class="card-title">Filtros de busqueda:</h5>
        <ul>
          <li>ID</li>
          <li>Nombre</li>
          <li>Empresa:
            <ul>
              <li>rfc</li>
              <li>Razon social</li>
            </ul>
          </li>
        </ul>
    </div>
  </div>
{% endblock %}

{% block  content %}

<div id="ContactoList">
  <h5 class="my-2">
    Buscar Contacto:
    <div class="form-inline my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="id, nombre, empresa"
        v-model="search_term" aria-label="Buscar">
      <button class="btn btn-outline-success my-sm-0"
        v-on:click.prevent="getContactoList()">Buscar</button>
    </div>
  </h5>
  <div >
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nombre</th>
          <th scope="col">Empresa</th>
        </tr>
        <tbody >
          <tr v-for="contacto in contactoList">
            <th scope="col">
              <a :href="getContactoUrl(contacto)">${contacto.id}</a>
            </th>
            <th scope="col">${contacto.nombre}</th>
            <th scope="col">
              <a :href="getContactoEmpresaUrl(contacto)">${contacto.empresa.razon_social}</a>
            </th>
          </tr>
        </tbody>
      </thead>
    </table>
  </div>
</div>

{% endblock %}

{% block scripts %}
  {% load static %}
  <script src="{% static 'frontend/contacto_list.js' %}"></script>
{% endblock %}