gestor/urls.py
from django.urls import path, include

from . import routers
from . import views

from django.contrib.auth import views as auth_views

from wkhtmltopdf.views import PDFTemplateView

app_name = 'gestor'

urlpatterns = [
    path(
        'pdf/', 
        PDFTemplateView.as_view(
            template_name='gestor/producto/ProductoDetail.html', 
            filename='sss.pdf',
            cmd_options={'quiet': True,}
        )
        , name='pdf'),
    path('', views.HomeView.as_view(), name='home'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='gestor/base.html'), name='logout'),
]


urlpatterns += [
    path('empresa/', views.EmpresaCreate.as_view(), name='create_empresa'),
    path('empresa/<slug:rfc>/', views.EmpresaContactoList.as_view(), name='detail_empresa'),
    path('empresa/<slug:rfc>/actualizar/', views.EmpresaUpdate.as_view(), name='update_empresa'),
    path('empresa/<slug:rfc>/eliminar/', views.EmpresaDelete.as_view(), name='delete_empresa'),
    path('empresas/', views.EmpresaList.as_view(), name='list_empresa'),
]

urlpatterns += [
    path('empresa/<slug:rfc>/archivo/', views.EmpresaArchivoCreate.as_view(), name='upload_empresa_archivo'),
    path('empresa/<slug:rfc>/archivos/', views.EmpresaArchivoList.as_view(), name='list_empresa_archivo'),
]

urlpatterns += [
    path('contactos/', views.ContactoList.as_view(), name='list_contacto'),
    path('empresa/<slug:rfc>/contactos/', views.EmpresaContactoList.as_view(), name='list_contacto_empresa'),
    path('empresa/<slug:rfc>/contacto/', views.ContactoCreate.as_view(), name='create_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/', views.ContactoDetail.as_view(), name='detail_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/actualizar/', views.ContactoUpdate.as_view(), name='update_contacto'),
    path('empresa/<slug:rfc>/contacto/<int:id>/eliminar/', views.ContactoDelete.as_view(), name='delete_contacto'),
]

urlpatterns += [
    path('productos/', views.ProductoList.as_view(), name='list_producto'),
    path('producto/', views.ProductoCreate.as_view(), name='create_producto'),
    path('producto/<int:id>/', views.ProductoUpdate.as_view(), name='detail_producto'),
    path('producto/<int:id>/actualizar/', views.ProductoUpdate.as_view(), name='update_producto'),
    path('producto/<int:id>/eliminar/', views.ProductoDelete.as_view(), name='delete_producto'),
]

urlpatterns += [
    path('cotizaciones/', views.CotizacionList.as_view(), name='list_cotizacion'),
    path('empresa/<slug:rfc>/cotizaciones/', views.EmpresaCotizacionList.as_view(), name='list_cotizacion_empresa'),
    path('empresa/<slug:rfc>/cotizacion/', views.CotizacionCreate.as_view(), name='create_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/', views.CotizacionDetail.as_view(), name='detail_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/actualizar/', views.CotizacionUpdate.as_view(), name='update_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto_cotizado/<int:id>/eliminar/', views.ProductoCotizadoDelete.as_view(), name='delete_prodcuto_cotizado'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto_cotizado/<int:id>/actualizar/', views.ProductoCotizadoUpdate.as_view(), name='update_producto_cotizado'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/producto/<int:id>/agregar/', views.ProductoAdd.as_view(), name='add_producto'),
]

urlpatterns += [
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/pdf/', views.CotizacionGeneratePDF.as_view(), name='generate_pdf_cotizacion'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/pdf/template/', views.CotizacionGeneratePDFView.as_view(), name='template_pdf_cotizacion'),
]

urlpatterns += [
    path('facturas/', views.FacturaList.as_view(), name='list_factura'),
    path('empresa/<slug:rfc>/facturas/', views.EmpresaFacturaList.as_view(), name='list_factura_empresa'),
    path('empresa/<slug:rfc>/cotizacion/<int:pk>/facturar/', views.FacturaCreate.as_view(), name='create_factura'),
    path('empresa/<slug:rfc>/factura/<int:id>/', views.FacturaDetail.as_view(), name='detail_factura'),
    path('empresa/<slug:rfc>/factura/<int:id>/archivo/', views.FacturaArchivosUpload.as_view(), name='upload_archivo'),
]

urlpatterns += [
    path('api/', include(routers.router.urls)),
]

revolucion/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestor/', include('gestor.urls')),
]

gestor/models.py
from django.db import models

from django.contrib.auth.models import User

from .utils import empresa_directory_path
from .utils import update_producto_cotizado, update_cotizacion
from .utils import get_descripcion

# Dictionaries
class CatalogoClaveProducto(models.Model):
    clave = models.IntegerField(primary_key=True)
    descripcion = models.CharField(max_length=20)

    def __str__(self):
        return '%d' % (self.clave)

#Datos Escenciales para el funcionamiento

class Empresa(models.Model):
    rfc = models.CharField(
        max_length=13,
        primary_key=True,
    )
    razon_social = models.CharField(max_length=40)
    nombre_comercial = models.CharField(
        max_length=40,
        blank=True, 
        null=True,
    )
    correo = models.EmailField(max_length=40)
    telefono = models.CharField(max_length=22)
    BANCOS = (
        (1, 'Bancomer'),
        (2, 'Banamex'),
        (3, 'Banorte'),
        (3, 'IXE'),
        (0, 'N/A'),
    )
    banco = models.IntegerField(
        choices=BANCOS,
        default=0,
    )
    referencia_bancaria = models.IntegerField(default = -1)
    CUIDAD_ESTADO = (
        (1, 'CDMX/CDMX'),
        (2, 'Estado de México/Toluca'),
    )
    USOS_CDFI = (
        ('P01', 'Por definir'),
        ('D10', 'Pagos por servicios educativos (colegiaturas)'),
        ('D09', 'Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones'),
        ('D08', 'Gastos de transportación escolar obligatoria'),
        ('D07', 'Primas por seguros de gastos médicos'),
        ('D06', 'Aportaciones voluntarias al SAR'),
        ('D05', 'Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)'),
        ('D04', 'Donativos'),
        ('D03', 'Gastos funerales'),
        ('D02', 'Gastos médicos por incapacidad o discapacidad'),
        ('D01', 'Honorarios médicos, dentales y gastos hospitalarios'),
        ('I08', 'Otra maquinaria y equipo'),
        ('I07', 'Comunicaciones satelitales'),
        ('I06', 'Comunicaciones telefónicas'),
        ('I05', 'Dados, troqueles, moldes, matrices y herramental'),
        ('I04', 'Equipo de cómputo y accesorios'),
        ('I03', 'Equipo de transporte'),
        ('I02', 'Mobiliario y equipo de oficina por inversiones'),
        ('I01', 'Construcciones'),
        ('G03', 'Gastos en general'),
        ('G02', 'Devoluciones, descuentos o bonificaciones'),
        ('G01', 'Adquisición de mercancías'),
    )
    uso_cdfi = models.CharField(
        max_length=3,
        choices=USOS_CDFI,
        default='P01',
    )
    FORMAS_PAGO = (
        (0, 'Efectivo'),
        (1, 'Cheque nominativo'),
        (2, 'Transferencia electrónicade fondos'),
        (3, 'Por definir'),
    )
    forma_pago = models.IntegerField(
        choices=FORMAS_PAGO,
        default=0,
    )
    METODOS_PAGO = (
        (0, 'PUE'),
        (1, 'PPD'),
    )
    metodo_pago = models.IntegerField(
        choices=METODOS_PAGO,
        default=0,
    )
    TIPOS_COMPROBANTE = (
        (0, 'I'),
        (1, 'E'),
        (2, 'T'),
        (3, 'P'),
        (4, 'N'),
    )
    tipo_comprobante = models.IntegerField(
        choices=TIPOS_COMPROBANTE,
        default=0,
    )
    cuidad_estado = models.IntegerField(
        choices=CUIDAD_ESTADO,
        default=1,
    )
    cp = models.IntegerField(default=-1)
    direccion = models.CharField(
        max_length=100,
        blank=True, 
        null=True,
    )
    direccion_entrega = models.CharField(
        max_length=100,
        blank=True, 
        null=True,
    )
    empresas_asociadas = models.ManyToManyField(
        "Empresa",
        related_name='emprsas_asociadas',
        blank=True, 
    )
    extra_1 = models.TextField(
        max_length=150,
        blank=True, null=True,
    )
    extra_2 = models.TextField(
        max_length=150,
        blank=True, null=True,
    )
    extra_3 = models.TextField(
        max_length=150,
        blank=True, null=True,
    )

    def __str__(self):
        return '%s' % self.rfc

class EmpresaArchivo(models.Model):
    empresa = models.ForeignKey(
        Empresa,
        on_delete=models.CASCADE,
        related_name='archivos',
    )
    archivo = models.FileField(upload_to=empresa_directory_path)
    fecha = models.DateField(auto_now_add=True)


class Contacto(models.Model):
    empresa = models.ForeignKey(
        Empresa,
        on_delete=models.CASCADE,
    )
    nombre = models.CharField(max_length=23)
    correo = models.EmailField(max_length=40)
    extension = models.CharField(
        max_length=5,
        blank=True, 
        null=True,
    )
    telefono = models.CharField(max_length=20)
    celular = models.CharField(
        max_length=20,
        blank=True, 
        null=True,
    )
    PREFIJO_CHOICES = (
        (0, ''),
        (1, 'Sr.'),
        (2, 'Sra.'),
        (3, 'Lic.'),
        (4, 'Ing.'),
    )
    prefijo = models.IntegerField(
        choices=PREFIJO_CHOICES,
        default=0,
    )
    puesto = models.CharField(
        max_length=20,
    )
    extra = models.TextField(
        max_length=150,
        blank=True, 
        null=True,
    )

    def __str__(self):
        return '%d[Nombre:%s]' % (self.id, self.nombre)

# Producto

class Producto(models.Model):
    numero_parte = models.CharField(max_length=40)
    TIPOS_PRODUCTO = (
        ('Prd', 'Producto'),
        ('Srv', 'Servicio'),
    )
    tipo_producto = models.CharField(
        max_length=3,
        choices=TIPOS_PRODUCTO,
        default='Prd',
    )
    UNIDADES_MEDIDA = (
        ('H87', 'Pieza'),
        ('XBX', 'Caja'),
        ('O', 'Otro'),
        ('0', 'No Aplica'),
    )
    unidad_medida = models.CharField(
        max_length=3,
        choices=UNIDADES_MEDIDA,
        default='H87',
    )
    clave = models.ForeignKey(
        CatalogoClaveProducto,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    ALIMENTO_IVA = 0
    SIN_ESPECIFICAR_IVA = 16
    TIPOS_IVA = (
        (ALIMENTO_IVA, 'ALIMENTO(0%)'),
        (SIN_ESPECIFICAR_IVA, 'S/A(16%)'),
    )
    tipo_iva = models.IntegerField(
        choices=TIPOS_IVA,
        default=SIN_ESPECIFICAR_IVA,
    )
    descripcion = models.TextField(
        max_length=100,
        blank=True,
    )


# Cotización

class Cotizacion(models.Model):
    empresa = models.ForeignKey(
        Empresa,
        on_delete=models.SET_NULL,
        blank=True, 
        null=True,
        related_name='cotizaciones',
    )
    usuario = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    referencia = models.CharField(
        max_length=20,
        blank=True, 
        null=True,
    )
    fecha = models.DateField(auto_now_add=True)
    contacto = models.ForeignKey(
        Contacto,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    costo_operacion = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    monto_iva = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    subtotal = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00
    )
    ganancia = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    margen_ganancia = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    inversion = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00
    )
    is_factura = models.BooleanField(default=False)
    extras = models.TextField(
        max_length=300,
        blank=True,
        null=True,
    )

    def __str__(self):
        return '%d[Nombre:%s]' % (self.id,self.referencia)

    def save(self, *args, **kwargs):
        update_cotizacion(self)
        super(Cotizacion, self).save(*args, **kwargs)

# Cuando se cotize un producto, en costo debera de aparecer el costo del producto
# junto con el respectivo margen de ganancia
class ProductoCotizado(models.Model):
    cotizacion = models.ForeignKey(
        Cotizacion,
        on_delete=models.CASCADE,
        related_name='productos_cotizados',
    )
    producto = models.ForeignKey(
        Producto,
        on_delete = models.CASCADE,
    )
    provedor = models.ForeignKey(
        Empresa,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    disponibilidad = models.CharField(
        max_length=10,
    )
    precio = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    costo = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    margen_ganancia = models.PositiveIntegerField(default=0)
    cantidad = models.PositiveIntegerField(default=1)
    monto_iva = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=-1.00,
    )
    importe = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
    )
    descripcion = models.TextField(
        max_length=150,
        blank=True,
    )

    def get_descripcion(instance):
        return instance.producto.descripcion

    def __str__(self):
        return '%d[Cotizacion:%d]' % (self.id, self.cotizacion.id)

    def save(self, *args, **kwargs):
        update_producto_cotizado(self)
        super(ProductoCotizado, self).save(*args, **kwargs)
        cotizacion = self.cotizacion
        update_cotizacion(cotizacion)
        cotizacion.save()

    def delete(self, *args, **kwargs):
        cotizacion = self.cotizacion
        super(ProductoCotizado, self).delete(*args, **kwargs)
        update_cotizacion(cotizacion)
        cotizacion.save()


class Factura(models.Model):

templates/gestor/cotizacion/CotizacionDetail.html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block empresa_item_content %}
  <h2>
    Cotización:
    <a href="#">
      #{{cotizacion.id}}
    </a>
    <a class="btn btn-primary" href="{% url 'gestor:generate_pdf_cotizacion' empresa.rfc cotizacion.pk %}">
      PDF
    </a>
  </h2>
  <div class="container">
    {% if not cotizacion.is_factura %}
      {% if cotizacion.usuario == request.user %}
        <a class="btn btn-primary" href="{% url 'gestor:create_factura' empresa.rfc cotizacion.pk %}">
          Facturar
        </a>
        <a class="btn btn-primary" href="{% url 'gestor:update_cotizacion' empresa.rfc cotizacion.pk %}">
          Actualizar cotiación
        </a>
      {% endif %}
    {% else %}
      <h5>Factura:
        <a href="{% url 'gestor:detail_factura' cotizacion.empresa.rfc factura.id %}">
          #{{factura.id}}
        </a>
      </h5>
      <h6>
        Estado: {{factura.get_estado_display}}
      </h6>
    {% endif %}
  </div>
  <h3 class="my-1">Referencia: {{cotizacion.referencia}}</h3>
  <h4>Fecha: {{cotizacion.fecha }}</h4>
  <div class="container">
    <dl class="row">
      <dt class="col-sm-3">Uso de CDFI:</dt>
      <dd class="col-sm-9">{{empresa.get_uso_cdfi_display}}</dd>

      <dt class="col-sm-3">Forma de pago:</dt>
      <dd class="col-sm-9">{{empresa.get_forma_pago_display}}</dd>

      <dt class="col-sm-3">Método de pago:</dt>
      <dd class="col-sm-9">{{empresa.get_metodo_pago_display}}</dd>

      <dt class="col-sm-3">Tipo de comprobante:</dt>
      <dd class="col-sm-9">{{empresa.get_tipo_comprobante_display}}</dd>

      <dt class="col-sm-3">Extras:</dt>
      <dd class="col-sm-9">{{cotizacion.extras}}</dd>
    </dl>
  </div>
  <div class="container">
    {% if not cotizacion.contacto is None %}
      <h5>Contacto:
        <a href="{% url 'gestor:detail_contacto' empresa.rfc cotizacion.contacto.id %}">
          {{cotizacion.contacto.nombre}}
        </a>
      </h5>
      <h6>Celular: {{cotizacion.contacto.numero }}<h6>
    {% endif %}
  </div>
  <div class="container">
    {% if not cotizacion.usuario is None %}
      <h4>
        Usuario: {{cotizacion.usuario.username }}
      </h4>
    {% endif %}
  </div>
  <h5>Prodcutos cotizados: </h5>
  <span cotizacion_id="{{cotizacion.id}}"></span>
  <div>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Producto</th>
          <th scope="col">Costo</th>
          <th scope="col">%&#x25B2;</th>
          <th scope="col">Provedor</th>
          <th scope="col">Disponibilidad</th>
          <th scope="col">IVA</th>
          <th scope="col">Precio</th>
          <th scope="col">Cantidad</th>
          <th scope="col">IVA</th>
          <th scope="col">Importe</th>
        </tr>
      </thead>
      <tbody>
        {% for producto_cotizado in producto_cotizado_list %}
          <tr>
            <th scope="col">
              <a href="#" data-toggle="modal" data-target="#ActionsModal{{producto_cotizado.id}}">
                {{producto_cotizado.producto.numero_parte}}
              </a>
              <!-- ActionsModal -->
              <div class="modal fade" id="ActionsModal{{producto_cotizado.id}}" tabindex="-1" role="dialog" aria-labelledby="actionsModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="actionsModalLabel">{{producto_cotizado.id}}</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <div class="container">
                        <h5>Producto: {{producto_cotizado.producto.numero_parte}}</h5>
                        <div class="container">
                          <h6>Clave: {{producto_cotizado.producto.clave}}</h6>
                          <h6>IVA: %{{producto_cotizado.producto.tipo_iva}}</h6>
                          <p>Descripción: {{producto_cotizado.producto.descripcion}}</p>
                        </div>
                        <h5>Costo: ${{producto_cotizado.costo}}</h5>
                        <div class="container">
                          <h6>Margen de ganancia: %{{producto_cotizado.margen_ganancia}}</h6>
                          <h6>Precio: ${{producto_cotizado.precio}}</h6>
                          <h6>Cantidad: {{producto_cotizado.cantidad}}</h6>
                          <h5>Monto IVA: ${{producto_cotizado.monto_iva}}</h5>
                        </div>
                        <div>
                          <p>Descripción:{{producto_cotizado.descripcion}}</p>
                        </div>
                        <h4>Importe: ${{producto_cotizado.importe}}</h4>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      {% if not cotizacion.is_factura %}
                          <a class="btn btn-danger"
                            href="{%url 'gestor:delete_prodcuto_cotizado' empresa.rfc cotizacion.id producto_cotizado.id %}">
                            Eliminar
                          </a>
                          <a class="btn btn-dark"
                            href="{% url 'gestor:update_producto_cotizado' empresa.rfc cotizacion.id producto_cotizado.id %}">
                            Editar
                          </a>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </th>
            <th scope="col">${{producto_cotizado.costo}}</th>
            <th scope="col">%{{producto_cotizado.margen_ganancia}}</th>
            <th scope="col">{{producto_cotizado.provedor.rfc}}</th>
            <th scope="col">{{producto_cotizado.disponibilidad}}</th>
            <th scope="col">%{{producto_cotizado.producto.tipo_iva}}</th>
            <th scope="col">${{producto_cotizado.precio}}</th>
            <th scope="col">{{producto_cotizado.cantidad}}</th>
            <th scope="col">${{producto_cotizado.monto_iva}}</th>
            <th scope="col">${{producto_cotizado.importe}}</th>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="float-right">
      <h6>Costo de operación: ${{cotizacion.costo_operacion}}</h6>
      <h5>Monto IVA: ${{cotizacion.monto_iva}}</h5>
      <h4>SubTotal: ${{cotizacion.subtotal}}</h4>
      <h3>Total: ${{cotizacion.total}}</h3>
    </div>
  </div>
  {% if not cotizacion.is_factura and cotizacion.usuario == request.user %}
    <div id="BuscarProducto" class="container">
      <h5 class="my-2">
        Buscar Producto:
        <div class="form-inline my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Producto"
            v-model="search_term" aria-label="Buscar">
          <button class="btn btn-outline-success my-sm-0"
            v-on:click.prevent="searchProducto()">Buscar</button>
        </div>
      </h5>
      <div class="container">
        <table class="table">
          <tr>
            <th scope="col">Número de parte</th>
            <th scope="col">T/P</th>
            <th scope="col">Clave</th>
            <th scope="col">U/M</th>
            <th scope="col">IVA</th>
            <th scope="col">Acciones</th>
          </tr>
          <tbody>
            <tr v-for="producto in productoSearchList">
              <th scope="col">${producto.numero_parte}</th>
              <th scope="col">${producto.tipo_producto}</th>
              <th scope="col">${producto.clave}</th>
              <th scope="col">${producto.unidad_medida}</th>
              <th scope="col">${producto.tipo_iva}</th>
              <th scope="col">
                <button class="btn btn-info">?</button>
                <a class="btn btn-dark" :href="getProductoAddUrl('{{empresa.rfc}}',{{cotizacion.id}}, producto)">+</a>
              </th>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}
{% endblock %}

{% block scripts %}
  {% load static %}
  <script src="{% static 'frontend/cotizacion/cotizacion_detail.js' %}"></script>
{% endblock %}

templates/gestor/cotizacion/CotizacionList(Empresa).html
{% extends "gestor/empresa/EmpresaDetail.html" %}

{% block empresa_item_content %}

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'gestor:list_factura_empresa' empresa.rfc %}">Facturas</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Cotizaciones</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'gestor:list_contacto_empresa' empresa.rfc %}">Contactos</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="{% url 'gestor:list_empresa_archivo' empresa.rfc %}">Extras</a>
  </li>
</ul>
<div class="my-2">
  <h5>
    Cotizaciones:
  </h5>
</div>

<table class="table table-hover" style="width:100%">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Referencia</th>
        <th scope="col">Fecha</th>
        <th scope="col">Usuario</th>
        <th scope="col">Contacto</th>
        <th scope="col">Ganancia</th>
        <th scope="col">Subtotal</th>
        <th scope="col">Total</th>
      </tr>
    </thead>
    {% for cotizacion in object_list %}
      <tr>
        {% if cotizacion.is_factura %}
          <th scope="col" class="table-success">
            <a href="{% url 'gestor:detail_cotizacion' empresa.rfc cotizacion.id %}">{{cotizacion.id}}</a>
          </th>
        {% else %}
          <th scope="col" class="table-danger">
            <a href="{% url 'gestor:detail_cotizacion' empresa.rfc cotizacion.id %}">{{cotizacion.id}}</a>
          </th>
        {% endif %}
        <th scope="col">
          {{cotizacion.referencia}}
        </th>
        <th scope="col">
          {{cotizacion.fecha}}
        </th>
        <th scope="col">
          {{cotizacion.usuario.username}}
        </th>
        <th scope="col">
          {{cotizacion.contacto.nombre}}
        </th>
        <th scope="col">
          ${{cotizacion.ganancia}}
        </th>
        <th scope="col">
          ${{cotizacion.subtotal}}
        </th>
        <th scope="col">
          ${{cotizacion.total}}
        </th>
      </tr>
    {% endfor %}
  </table>

</div>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ i }} <span class="sr-only">actual</span></a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Siguiente</span>
        </a>
      </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Siguiente</span>
      </a>
    </li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}